import { describe, expect, it } from 'vitest'
import { computeRatings } from './computeRatings'
import type { RatingGame } from './computeRatings'

// Exact same fixture as scripts/test_ratings.py's TEN_U_B_GAMES (real 10U B
// preseason results, Labor Day weekend 2026). Game() there is (home, away,
// home_goals, away_goals).
const TEN_U_B_GAMES: RatingGame[] = [
  { home: 'Stockton Colts 10-1', away: 'San Jose Jr Sharks Girls 10G-1', homeGoals: 12, awayGoals: 1 },
  { home: 'Oakland Bears 10-2', away: 'Tri Valley Blue Devils 10-3', homeGoals: 5, awayGoals: 3 },
  { home: 'San Jose Jr Sharks 10-6', away: 'Stockton Colts Girls 10G-1', homeGoals: 11, awayGoals: 1 },
  { home: 'Santa Clara Blackhawks 10-2', away: 'San Francisco Sabercats 10-2', homeGoals: 11, awayGoals: 1 },
  { home: 'Santa Rosa Flyers 10-2', away: 'Vacaville Jets 10-2', homeGoals: 12, awayGoals: 8 },
  { home: 'Tri Valley Lady Blue Devils 10G-1', away: 'San Jose Jr Sharks 10-5', homeGoals: 5, awayGoals: 0 },
  { home: 'Stockton Colts 10-1', away: 'San Mateo Black Stars 10-3', homeGoals: 13, awayGoals: 0 },
  { home: 'Capital Thunder 10-2', away: 'Vacaville Jets 10-2', homeGoals: 11, awayGoals: 4 },
  { home: 'Fresno Jr Monsters 10-1', away: 'Santa Clara Blackhawks 10-2', homeGoals: 8, awayGoals: 1 },
  { home: 'San Jose Jr Sharks 10-6', away: 'Lake Tahoe Grizzlies 10-2', homeGoals: 7, awayGoals: 4 },
  { home: 'Stockton Colts Girls 10G-1', away: 'Fresno Jr Monsters Girls 10G-1', homeGoals: 13, awayGoals: 3 },
  { home: 'Tri Valley Blue Devils 10-3', away: 'San Francisco Sabercats 10-2', homeGoals: 3, awayGoals: 2 },
  { home: 'San Jose Jr Sharks 10-5', away: 'Capital Thunder 10-2', homeGoals: 7, awayGoals: 2 },
  { home: 'Lake Tahoe Grizzlies 10-2', away: 'San Mateo Black Stars 10-3', homeGoals: 14, awayGoals: 0 },
  { home: 'Tri Valley Lady Blue Devils 10G-1', away: 'Oakland Bears 10-2', homeGoals: 12, awayGoals: 0 },
  { home: 'San Jose Jr Sharks Girls 10G-1', away: 'Fresno Jr Monsters Girls 10G-1', homeGoals: 11, awayGoals: 1 },
  { home: 'Fresno Jr Monsters 10-1', away: 'Santa Rosa Flyers 10-2', homeGoals: 11, awayGoals: 2 },
  { home: 'Stockton Colts 10-1', away: 'Oakland Bears 10-2', homeGoals: 14, awayGoals: 3 },
  { home: 'San Francisco Sabercats 10-2', away: 'Stockton Colts Girls 10G-1', homeGoals: 9, awayGoals: 4 },
  { home: 'Santa Clara Blackhawks 10-2', away: 'Tri Valley Blue Devils 10-3', homeGoals: 9, awayGoals: 3 },
  { home: 'San Jose Jr Sharks 10-5', away: 'Vacaville Jets 10-2', homeGoals: 12, awayGoals: 1 },
  { home: 'San Jose Jr Sharks 10-6', away: 'Santa Rosa Flyers 10-2', homeGoals: 7, awayGoals: 1 },
  { home: 'Tri Valley Lady Blue Devils 10G-1', away: 'Capital Thunder 10-2', homeGoals: 7, awayGoals: 0 },
  { home: 'Fresno Jr Monsters 10-1', away: 'Lake Tahoe Grizzlies 10-2', homeGoals: 13, awayGoals: 0 },
  { home: 'Fresno Jr Monsters Girls 10G-1', away: 'San Mateo Black Stars 10-3', homeGoals: 5, awayGoals: 3 },
  { home: 'San Mateo Black Stars 10-3', away: 'San Jose Jr Sharks Girls 10G-1', homeGoals: 9, awayGoals: 0 },
]

// Generated by running the real Python `compute_ratings` on the identical
// fixture (scripts/test_ratings.py's TEN_U_B_GAMES) -- the golden output
// this port must match, to 3 decimals, for every team.
const EXPECTED_RATINGS: Record<string, number> = {
  'Fresno Jr Monsters 10-1': 6.507,
  'Tri Valley Lady Blue Devils 10G-1': 4.969,
  'Stockton Colts 10-1': 4.64,
  'San Jose Jr Sharks 10-6': 4.085,
  'Santa Clara Blackhawks 10-2': 1.641,
  'San Jose Jr Sharks 10-5': 1.096,
  'Lake Tahoe Grizzlies 10-2': 1.069,
  'Santa Rosa Flyers 10-2': -1.495,
  'Capital Thunder 10-2': -1.624,
  'San Francisco Sabercats 10-2': -1.661,
  'Oakland Bears 10-2': -1.664,
  'Stockton Colts Girls 10G-1': -1.682,
  'San Mateo Black Stars 10-3': -1.78,
  'San Jose Jr Sharks Girls 10G-1': -1.83,
  'Tri Valley Blue Devils 10-3': -2.688,
  'Fresno Jr Monsters Girls 10G-1': -3.468,
  'Vacaville Jets 10-2': -6.115,
}

describe('computeRatings', () => {
  it('matches the real Python compute_ratings output exactly, to 3 decimals, for every team', () => {
    const result = computeRatings(TEN_U_B_GAMES)
    expect(Object.keys(result).sort()).toEqual(Object.keys(EXPECTED_RATINGS).sort())
    for (const [name, expected] of Object.entries(EXPECTED_RATINGS)) {
      expect(result[name]).toBeCloseTo(expected, 3)
    }
  })

  it('returns an empty object for no games', () => {
    expect(computeRatings([])).toEqual({})
  })

  it('caps the margin at +/-GOAL_CAP before it affects the rating', () => {
    const blowout = computeRatings([{ home: 'A', away: 'B', homeGoals: 50, awayGoals: 0 }])
    const capped = computeRatings([{ home: 'A', away: 'B', homeGoals: 7, awayGoals: 0 }])
    expect(blowout.A).toBeCloseTo(capped.A, 5)
    expect(blowout.B).toBeCloseTo(capped.B, 5)
  })

  it('centers ratings around zero', () => {
    const result = computeRatings(TEN_U_B_GAMES)
    const mean = Object.values(result).reduce((a, b) => a + b, 0) / Object.values(result).length
    expect(mean).toBeCloseTo(0, 2)
  })
})
